/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { licensesActivate } from "../funcs/licensesActivate.js";
import { licensesDeactivate } from "../funcs/licensesDeactivate.js";
import { licensesListInstances } from "../funcs/licensesListInstances.js";
import { licensesValidate } from "../funcs/licensesValidate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Licenses extends ClientSDK {
  /**
   * Activates a license key.
   *
   * @remarks
   * Activate a license key for a specific device or instance. Register new activations and track usage limits.
   */
  async activate(
    request: components.ActivateLicenseRequestEntity,
    options?: RequestOptions,
  ): Promise<components.LicenseEntity> {
    return unwrapAsync(licensesActivate(
      this,
      request,
      options,
    ));
  }

  /**
   * Deactivate a license key instance.
   *
   * @remarks
   * Remove a device activation from a license key. Free up activation slots for new devices.
   */
  async deactivate(
    request: components.DeactivateLicenseRequestEntity,
    options?: RequestOptions,
  ): Promise<components.LicenseEntity> {
    return unwrapAsync(licensesDeactivate(
      this,
      request,
      options,
    ));
  }

  /**
   * Validates a license key or instance.
   *
   * @remarks
   * Verify if a license key is valid and active for a specific instance. Check activation status and expiration.
   */
  async validate(
    request: components.ValidateLicenseRequestEntity,
    options?: RequestOptions,
  ): Promise<components.LicenseEntity> {
    return unwrapAsync(licensesValidate(
      this,
      request,
      options,
    ));
  }

  /**
   * List license instances.
   *
   * @remarks
   * Retrieve a paginated list of instances (activations) for a license key. Use an instance id from this list to deactivate it via the deactivate endpoint.
   */
  async listInstances(
    id: string,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListLicenseInstancesResponse, { page: number }>
  > {
    return unwrapResultIterator(licensesListInstances(
      this,
      id,
      pageNumber,
      pageSize,
      options,
    ));
  }
}
