/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsGetById } from "../funcs/transactionsGetById.js";
import { transactionsRefund } from "../funcs/transactionsRefund.js";
import { transactionsSearch } from "../funcs/transactionsSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Transactions extends ClientSDK {
  /**
   * Get a transaction by ID
   *
   * @remarks
   * Retrieve a single transaction by ID. View payment details, status, and associated order information.
   */
  async getById(
    transactionId: string,
    options?: RequestOptions,
  ): Promise<components.TransactionEntity> {
    return unwrapAsync(transactionsGetById(
      this,
      transactionId,
      options,
    ));
  }

  /**
   * List all transactions
   *
   * @remarks
   * Search and retrieve payment transactions. Filter by customer, product, date range, and status.
   */
  async search(
    customerId?: string | undefined,
    orderId?: string | undefined,
    productId?: string | undefined,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.SearchTransactionsResponse, { page: number }>
  > {
    return unwrapResultIterator(transactionsSearch(
      this,
      customerId,
      orderId,
      productId,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * Refund a payment
   *
   * @remarks
   * Issue a full refund for a payment, identified by its transaction ID. The full remaining refundable amount is resolved automatically. Returns `pending` when the payment provider confirms the refund asynchronously.
   */
  async refund(
    request: components.CreateRefundRequestEntity,
    options?: RequestOptions,
  ): Promise<components.RefundResponseEntity> {
    return unwrapAsync(transactionsRefund(
      this,
      request,
      options,
    ));
  }
}
