/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateProductRequest = {
  /**
   * Optional key that makes retries return the originally created product instead of creating a duplicate.
   */
  idempotencyKey?: string | undefined;
  /**
   * Product creation payload
   */
  createProductRequestEntity: components.CreateProductRequestEntity;
};

/** @internal */
export const CreateProductRequest$inboundSchema: z.ZodType<
  CreateProductRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Idempotency-Key": z.string().optional(),
  CreateProductRequestEntity:
    components.CreateProductRequestEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Idempotency-Key": "idempotencyKey",
    "CreateProductRequestEntity": "createProductRequestEntity",
  });
});
/** @internal */
export type CreateProductRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  CreateProductRequestEntity: components.CreateProductRequestEntity$Outbound;
};

/** @internal */
export const CreateProductRequest$outboundSchema: z.ZodType<
  CreateProductRequest$Outbound,
  z.ZodTypeDef,
  CreateProductRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  createProductRequestEntity:
    components.CreateProductRequestEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "Idempotency-Key",
    createProductRequestEntity: "CreateProductRequestEntity",
  });
});

export function createProductRequestToJSON(
  createProductRequest: CreateProductRequest,
): string {
  return JSON.stringify(
    CreateProductRequest$outboundSchema.parse(createProductRequest),
  );
}
export function createProductRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateProductRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProductRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProductRequest' from JSON`,
  );
}
