/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAffiliatesRequest = {
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

export type ListAffiliatesResponse = {
  result: components.AffiliateListEntity;
};

/** @internal */
export const ListAffiliatesRequest$inboundSchema: z.ZodType<
  ListAffiliatesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_number: z.number().default(1),
  page_size: z.number().default(50),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
  });
});
/** @internal */
export type ListAffiliatesRequest$Outbound = {
  page_number: number;
  page_size: number;
};

/** @internal */
export const ListAffiliatesRequest$outboundSchema: z.ZodType<
  ListAffiliatesRequest$Outbound,
  z.ZodTypeDef,
  ListAffiliatesRequest
> = z.object({
  pageNumber: z.number().default(1),
  pageSize: z.number().default(50),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
  });
});

export function listAffiliatesRequestToJSON(
  listAffiliatesRequest: ListAffiliatesRequest,
): string {
  return JSON.stringify(
    ListAffiliatesRequest$outboundSchema.parse(listAffiliatesRequest),
  );
}
export function listAffiliatesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAffiliatesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAffiliatesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAffiliatesRequest' from JSON`,
  );
}

/** @internal */
export const ListAffiliatesResponse$inboundSchema: z.ZodType<
  ListAffiliatesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.AffiliateListEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListAffiliatesResponse$Outbound = {
  Result: components.AffiliateListEntity$Outbound;
};

/** @internal */
export const ListAffiliatesResponse$outboundSchema: z.ZodType<
  ListAffiliatesResponse$Outbound,
  z.ZodTypeDef,
  ListAffiliatesResponse
> = z.object({
  result: components.AffiliateListEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listAffiliatesResponseToJSON(
  listAffiliatesResponse: ListAffiliatesResponse,
): string {
  return JSON.stringify(
    ListAffiliatesResponse$outboundSchema.parse(listAffiliatesResponse),
  );
}
export function listAffiliatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAffiliatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAffiliatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAffiliatesResponse' from JSON`,
  );
}
