/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListLicenseInstancesRequest = {
  /**
   * The unique identifier of the license key
   */
  id: string;
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

export type ListLicenseInstancesResponse = {
  result: components.LicenseInstanceListEntity;
};

/** @internal */
export const ListLicenseInstancesRequest$inboundSchema: z.ZodType<
  ListLicenseInstancesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  page_number: z.number().default(1),
  page_size: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
  });
});
/** @internal */
export type ListLicenseInstancesRequest$Outbound = {
  id: string;
  page_number: number;
  page_size: number;
};

/** @internal */
export const ListLicenseInstancesRequest$outboundSchema: z.ZodType<
  ListLicenseInstancesRequest$Outbound,
  z.ZodTypeDef,
  ListLicenseInstancesRequest
> = z.object({
  id: z.string(),
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
  });
});

export function listLicenseInstancesRequestToJSON(
  listLicenseInstancesRequest: ListLicenseInstancesRequest,
): string {
  return JSON.stringify(
    ListLicenseInstancesRequest$outboundSchema.parse(
      listLicenseInstancesRequest,
    ),
  );
}
export function listLicenseInstancesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListLicenseInstancesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLicenseInstancesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLicenseInstancesRequest' from JSON`,
  );
}

/** @internal */
export const ListLicenseInstancesResponse$inboundSchema: z.ZodType<
  ListLicenseInstancesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.LicenseInstanceListEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListLicenseInstancesResponse$Outbound = {
  Result: components.LicenseInstanceListEntity$Outbound;
};

/** @internal */
export const ListLicenseInstancesResponse$outboundSchema: z.ZodType<
  ListLicenseInstancesResponse$Outbound,
  z.ZodTypeDef,
  ListLicenseInstancesResponse
> = z.object({
  result: components.LicenseInstanceListEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listLicenseInstancesResponseToJSON(
  listLicenseInstancesResponse: ListLicenseInstancesResponse,
): string {
  return JSON.stringify(
    ListLicenseInstancesResponse$outboundSchema.parse(
      listLicenseInstancesResponse,
    ),
  );
}
export function listLicenseInstancesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListLicenseInstancesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLicenseInstancesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLicenseInstancesResponse' from JSON`,
  );
}
