/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAffiliateCommissionsRequest = {
  /**
   * The unique identifier of the affiliate
   */
  id: string;
  /**
   * The settlement status of the commission. `pending` while on hold, `approved` once cleared and available, `paid` once settled by a payout.
   */
  status?: components.CommissionStatus | undefined;
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

export type ListAffiliateCommissionsResponse = {
  result: components.CommissionListEntity;
};

/** @internal */
export const ListAffiliateCommissionsRequest$inboundSchema: z.ZodType<
  ListAffiliateCommissionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  status: components.CommissionStatus$inboundSchema.optional(),
  page_number: z.number().default(1),
  page_size: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
  });
});
/** @internal */
export type ListAffiliateCommissionsRequest$Outbound = {
  id: string;
  status?: string | undefined;
  page_number: number;
  page_size: number;
};

/** @internal */
export const ListAffiliateCommissionsRequest$outboundSchema: z.ZodType<
  ListAffiliateCommissionsRequest$Outbound,
  z.ZodTypeDef,
  ListAffiliateCommissionsRequest
> = z.object({
  id: z.string(),
  status: components.CommissionStatus$outboundSchema.optional(),
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
  });
});

export function listAffiliateCommissionsRequestToJSON(
  listAffiliateCommissionsRequest: ListAffiliateCommissionsRequest,
): string {
  return JSON.stringify(
    ListAffiliateCommissionsRequest$outboundSchema.parse(
      listAffiliateCommissionsRequest,
    ),
  );
}
export function listAffiliateCommissionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAffiliateCommissionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAffiliateCommissionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAffiliateCommissionsRequest' from JSON`,
  );
}

/** @internal */
export const ListAffiliateCommissionsResponse$inboundSchema: z.ZodType<
  ListAffiliateCommissionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.CommissionListEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListAffiliateCommissionsResponse$Outbound = {
  Result: components.CommissionListEntity$Outbound;
};

/** @internal */
export const ListAffiliateCommissionsResponse$outboundSchema: z.ZodType<
  ListAffiliateCommissionsResponse$Outbound,
  z.ZodTypeDef,
  ListAffiliateCommissionsResponse
> = z.object({
  result: components.CommissionListEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listAffiliateCommissionsResponseToJSON(
  listAffiliateCommissionsResponse: ListAffiliateCommissionsResponse,
): string {
  return JSON.stringify(
    ListAffiliateCommissionsResponse$outboundSchema.parse(
      listAffiliateCommissionsResponse,
    ),
  );
}
export function listAffiliateCommissionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAffiliateCommissionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAffiliateCommissionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAffiliateCommissionsResponse' from JSON`,
  );
}
