/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListCustomerCreditsAccountEntriesRequest = {
  id: string;
  /**
   * Maximum number of entries to return
   */
  limit?: number | undefined;
  /**
   * Cursor for forward pagination — entry ID to start after
   */
  startingAfter?: string | undefined;
  /**
   * Cursor for backward pagination — entry ID to end before
   */
  endingBefore?: string | undefined;
};

/** @internal */
export const ListCustomerCreditsAccountEntriesRequest$inboundSchema: z.ZodType<
  ListCustomerCreditsAccountEntriesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  limit: z.number().default(10),
  starting_after: z.string().optional(),
  ending_before: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "starting_after": "startingAfter",
    "ending_before": "endingBefore",
  });
});
/** @internal */
export type ListCustomerCreditsAccountEntriesRequest$Outbound = {
  id: string;
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
};

/** @internal */
export const ListCustomerCreditsAccountEntriesRequest$outboundSchema: z.ZodType<
  ListCustomerCreditsAccountEntriesRequest$Outbound,
  z.ZodTypeDef,
  ListCustomerCreditsAccountEntriesRequest
> = z.object({
  id: z.string(),
  limit: z.number().default(10),
  startingAfter: z.string().optional(),
  endingBefore: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    startingAfter: "starting_after",
    endingBefore: "ending_before",
  });
});

export function listCustomerCreditsAccountEntriesRequestToJSON(
  listCustomerCreditsAccountEntriesRequest:
    ListCustomerCreditsAccountEntriesRequest,
): string {
  return JSON.stringify(
    ListCustomerCreditsAccountEntriesRequest$outboundSchema.parse(
      listCustomerCreditsAccountEntriesRequest,
    ),
  );
}
export function listCustomerCreditsAccountEntriesRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ListCustomerCreditsAccountEntriesRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListCustomerCreditsAccountEntriesRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListCustomerCreditsAccountEntriesRequest' from JSON`,
  );
}
