/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RetrieveAffiliateRequest = {
  /**
   * The unique identifier of the affiliate
   */
  id: string;
};

/** @internal */
export const RetrieveAffiliateRequest$inboundSchema: z.ZodType<
  RetrieveAffiliateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type RetrieveAffiliateRequest$Outbound = {
  id: string;
};

/** @internal */
export const RetrieveAffiliateRequest$outboundSchema: z.ZodType<
  RetrieveAffiliateRequest$Outbound,
  z.ZodTypeDef,
  RetrieveAffiliateRequest
> = z.object({
  id: z.string(),
});

export function retrieveAffiliateRequestToJSON(
  retrieveAffiliateRequest: RetrieveAffiliateRequest,
): string {
  return JSON.stringify(
    RetrieveAffiliateRequest$outboundSchema.parse(retrieveAffiliateRequest),
  );
}
export function retrieveAffiliateRequestFromJSON(
  jsonString: string,
): SafeParseResult<RetrieveAffiliateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RetrieveAffiliateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RetrieveAffiliateRequest' from JSON`,
  );
}
