/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { affiliatesList } from "../../funcs/affiliatesList.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  pageNumber: z.number().default(1),
  pageSize: z.number().default(50),
};

export const tool$affiliatesList: ToolDefinition<typeof args> = {
  name: "affiliates-list",
  description: `List all affiliates

Retrieve a paginated list of your affiliates with their referral link, click and conversion counts, and lifetime commission. Affiliates who were invited but have not yet joined a program are not included.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await affiliatesList(
      client,
      args.pageNumber,
      args.pageSize,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
