/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { affiliatesRetrieve } from "../../funcs/affiliatesRetrieve.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$affiliatesRetrieve: ToolDefinition<typeof args> = {
  name: "affiliates-retrieve",
  description: `Retrieve an affiliate

Retrieve a single affiliate by ID, including referral link, click and conversion counts, and lifetime commission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await affiliatesRetrieve(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
