/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { affiliatesListCommissions } from "../../funcs/affiliatesListCommissions.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  status: components.CommissionStatus$inboundSchema.optional(),
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
};

export const tool$affiliatesListCommissions: ToolDefinition<typeof args> = {
  name: "affiliates-list-commissions",
  description: `List affiliate commissions

Retrieve a paginated list of an affiliate’s commissions. Filter by settlement status (pending, approved, paid).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await affiliatesListCommissions(
      client,
      args.id,
      args.status,
      args.pageNumber,
      args.pageSize,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
