/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { licensesListInstances } from "../../funcs/licensesListInstances.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
};

export const tool$licensesListInstances: ToolDefinition<typeof args> = {
  name: "licenses-list-instances",
  description: `List license instances.

Retrieve a paginated list of instances (activations) for a license key. Use an instance id from this list to deactivate it via the deactivate endpoint.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await licensesListInstances(
      client,
      args.id,
      args.pageNumber,
      args.pageSize,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
