/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsRefund } from "../../funcs/transactionsRefund.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateRefundRequestEntity$inboundSchema,
};

export const tool$transactionsRefund: ToolDefinition<typeof args> = {
  name: "transactions-refund",
  description: `Refund a payment

Issue a full refund for a payment, identified by its transaction ID. The full remaining refundable amount is resolved automatically. Returns \`pending\` when the payment provider confirms the refund asynchronously.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionsRefund(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
