/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AffiliateEntity,
  AffiliateEntity$inboundSchema,
  AffiliateEntity$Outbound,
  AffiliateEntity$outboundSchema,
} from "./affiliateentity.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";

export type AffiliateListEntity = {
  /**
   * List of affiliate items
   */
  items: Array<AffiliateEntity>;
  /**
   * Pagination details for the list
   */
  pagination: PaginationEntity;
};

/** @internal */
export const AffiliateListEntity$inboundSchema: z.ZodType<
  AffiliateListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(AffiliateEntity$inboundSchema),
  pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export type AffiliateListEntity$Outbound = {
  items: Array<AffiliateEntity$Outbound>;
  pagination: PaginationEntity$Outbound;
};

/** @internal */
export const AffiliateListEntity$outboundSchema: z.ZodType<
  AffiliateListEntity$Outbound,
  z.ZodTypeDef,
  AffiliateListEntity
> = z.object({
  items: z.array(AffiliateEntity$outboundSchema),
  pagination: PaginationEntity$outboundSchema,
});

export function affiliateListEntityToJSON(
  affiliateListEntity: AffiliateListEntity,
): string {
  return JSON.stringify(
    AffiliateListEntity$outboundSchema.parse(affiliateListEntity),
  );
}
export function affiliateListEntityFromJSON(
  jsonString: string,
): SafeParseResult<AffiliateListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AffiliateListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AffiliateListEntity' from JSON`,
  );
}
