/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EnvironmentMode,
  EnvironmentMode$inboundSchema,
  EnvironmentMode$outboundSchema,
} from "./environmentmode.js";

export type AffiliateEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: EnvironmentMode;
  /**
   * String representing the object's type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * The email address the affiliate was invited with.
   */
  email: string;
  /**
   * The display name of the affiliate, if set.
   */
  name?: string | null | undefined;
  /**
   * The affiliate's status within your program, reflecting their membership standing: `active`, `pending` (awaiting approval), `rejected`, `suspended`, or `inactive` (left or removed). Invited-but-not-yet-joined affiliates are not returned by this endpoint.
   */
  status: string;
  /**
   * The affiliate's unique referral code.
   */
  referralCode: string;
  /**
   * The affiliate's shareable referral link. Traffic arriving through it is attributed to this affiliate.
   */
  referralLink: string;
  /**
   * Total number of clicks recorded on the affiliate’s links.
   */
  clicks: number;
  /**
   * Total number of conversions attributed to the affiliate.
   */
  conversions: number;
  /**
   * Lifetime commission earned by the affiliate, in cents (1000 = $10.00), reported in a single primary currency (see `currency`). Affiliates earning in multiple currencies show only their highest-earning currency here; use the affiliate's commissions endpoint for the full per-currency breakdown.
   */
  earnings: number;
  /**
   * Three-letter ISO currency code, in uppercase, for the `earnings` amount. This is the affiliate's primary (highest-earning) currency; commissions in other currencies are listed individually on the commissions endpoint.
   */
  currency: string;
};

/** @internal */
export const AffiliateEntity$inboundSchema: z.ZodType<
  AffiliateEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$inboundSchema,
  object: z.string(),
  email: z.string(),
  name: z.nullable(z.string()).optional(),
  status: z.string(),
  referral_code: z.string(),
  referral_link: z.string(),
  clicks: z.number(),
  conversions: z.number(),
  earnings: z.number(),
  currency: z.string(),
}).transform((v) => {
  return remap$(v, {
    "referral_code": "referralCode",
    "referral_link": "referralLink",
  });
});
/** @internal */
export type AffiliateEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  email: string;
  name?: string | null | undefined;
  status: string;
  referral_code: string;
  referral_link: string;
  clicks: number;
  conversions: number;
  earnings: number;
  currency: string;
};

/** @internal */
export const AffiliateEntity$outboundSchema: z.ZodType<
  AffiliateEntity$Outbound,
  z.ZodTypeDef,
  AffiliateEntity
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$outboundSchema,
  object: z.string(),
  email: z.string(),
  name: z.nullable(z.string()).optional(),
  status: z.string(),
  referralCode: z.string(),
  referralLink: z.string(),
  clicks: z.number(),
  conversions: z.number(),
  earnings: z.number(),
  currency: z.string(),
}).transform((v) => {
  return remap$(v, {
    referralCode: "referral_code",
    referralLink: "referral_link",
  });
});

export function affiliateEntityToJSON(
  affiliateEntity: AffiliateEntity,
): string {
  return JSON.stringify(AffiliateEntity$outboundSchema.parse(affiliateEntity));
}
export function affiliateEntityFromJSON(
  jsonString: string,
): SafeParseResult<AffiliateEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AffiliateEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AffiliateEntity' from JSON`,
  );
}
