/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CommissionStatus,
  CommissionStatus$inboundSchema,
  CommissionStatus$outboundSchema,
} from "./commissionstatus.js";
import {
  EnvironmentMode,
  EnvironmentMode$inboundSchema,
  EnvironmentMode$outboundSchema,
} from "./environmentmode.js";

export type CommissionEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: EnvironmentMode;
  /**
   * String representing the object's type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * The ID of the affiliate this commission belongs to.
   */
  affiliate: string;
  /**
   * The commission amount in cents. 1000 = $10.00
   */
  amount: number;
  /**
   * Three-letter ISO currency code, in uppercase, for the commission amount.
   */
  currency: string;
  /**
   * The settlement status of the commission. `pending` while on hold, `approved` once cleared and available, `paid` once settled by a payout.
   */
  status: CommissionStatus;
  /**
   * The ID of the sale transaction that generated this commission, if available.
   */
  sale?: string | null | undefined;
  /**
   * Creation date of the commission as a timestamp.
   */
  createdAt: number;
};

/** @internal */
export const CommissionEntity$inboundSchema: z.ZodType<
  CommissionEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$inboundSchema,
  object: z.string(),
  affiliate: z.string(),
  amount: z.number(),
  currency: z.string(),
  status: CommissionStatus$inboundSchema,
  sale: z.nullable(z.string()).optional(),
  created_at: z.number(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type CommissionEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  affiliate: string;
  amount: number;
  currency: string;
  status: string;
  sale?: string | null | undefined;
  created_at: number;
};

/** @internal */
export const CommissionEntity$outboundSchema: z.ZodType<
  CommissionEntity$Outbound,
  z.ZodTypeDef,
  CommissionEntity
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$outboundSchema,
  object: z.string(),
  affiliate: z.string(),
  amount: z.number(),
  currency: z.string(),
  status: CommissionStatus$outboundSchema,
  sale: z.nullable(z.string()).optional(),
  createdAt: z.number(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function commissionEntityToJSON(
  commissionEntity: CommissionEntity,
): string {
  return JSON.stringify(
    CommissionEntity$outboundSchema.parse(commissionEntity),
  );
}
export function commissionEntityFromJSON(
  jsonString: string,
): SafeParseResult<CommissionEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommissionEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommissionEntity' from JSON`,
  );
}
