/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CommissionEntity,
  CommissionEntity$inboundSchema,
  CommissionEntity$Outbound,
  CommissionEntity$outboundSchema,
} from "./commissionentity.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";

export type CommissionListEntity = {
  /**
   * List of commission items
   */
  items: Array<CommissionEntity>;
  /**
   * Pagination details for the list
   */
  pagination: PaginationEntity;
};

/** @internal */
export const CommissionListEntity$inboundSchema: z.ZodType<
  CommissionListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(CommissionEntity$inboundSchema),
  pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export type CommissionListEntity$Outbound = {
  items: Array<CommissionEntity$Outbound>;
  pagination: PaginationEntity$Outbound;
};

/** @internal */
export const CommissionListEntity$outboundSchema: z.ZodType<
  CommissionListEntity$Outbound,
  z.ZodTypeDef,
  CommissionListEntity
> = z.object({
  items: z.array(CommissionEntity$outboundSchema),
  pagination: PaginationEntity$outboundSchema,
});

export function commissionListEntityToJSON(
  commissionListEntity: CommissionListEntity,
): string {
  return JSON.stringify(
    CommissionListEntity$outboundSchema.parse(commissionListEntity),
  );
}
export function commissionListEntityFromJSON(
  jsonString: string,
): SafeParseResult<CommissionListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommissionListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommissionListEntity' from JSON`,
  );
}
