/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The settlement status of the commission. `pending` while on hold, `approved` once cleared and available, `paid` once settled by a payout.
 */
export const CommissionStatus = {
  Pending: "pending",
  Approved: "approved",
  Paid: "paid",
} as const;
/**
 * The settlement status of the commission. `pending` while on hold, `approved` once cleared and available, `paid` once settled by a payout.
 */
export type CommissionStatus = ClosedEnum<typeof CommissionStatus>;

/** @internal */
export const CommissionStatus$inboundSchema: z.ZodNativeEnum<
  typeof CommissionStatus
> = z.nativeEnum(CommissionStatus);
/** @internal */
export const CommissionStatus$outboundSchema: z.ZodNativeEnum<
  typeof CommissionStatus
> = CommissionStatus$inboundSchema;
