/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateRefundRequestEntity = {
  /**
   * The unique identifier of the transaction to refund in full.
   */
  transactionId: string;
};

/** @internal */
export const CreateRefundRequestEntity$inboundSchema: z.ZodType<
  CreateRefundRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  transaction_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "transaction_id": "transactionId",
  });
});
/** @internal */
export type CreateRefundRequestEntity$Outbound = {
  transaction_id: string;
};

/** @internal */
export const CreateRefundRequestEntity$outboundSchema: z.ZodType<
  CreateRefundRequestEntity$Outbound,
  z.ZodTypeDef,
  CreateRefundRequestEntity
> = z.object({
  transactionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    transactionId: "transaction_id",
  });
});

export function createRefundRequestEntityToJSON(
  createRefundRequestEntity: CreateRefundRequestEntity,
): string {
  return JSON.stringify(
    CreateRefundRequestEntity$outboundSchema.parse(createRefundRequestEntity),
  );
}
export function createRefundRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<CreateRefundRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateRefundRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateRefundRequestEntity' from JSON`,
  );
}
