/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Error category
 */
export const CustomerCreditsErrorDetailDtoType = {
  InvalidRequestError: "invalid_request_error",
  ApiError: "api_error",
  AuthenticationError: "authentication_error",
  RateLimitError: "rate_limit_error",
} as const;
/**
 * Error category
 */
export type CustomerCreditsErrorDetailDtoType = ClosedEnum<
  typeof CustomerCreditsErrorDetailDtoType
>;

export type CustomerCreditsErrorDetailDto = {
  /**
   * Error category
   */
  type: CustomerCreditsErrorDetailDtoType;
  /**
   * Machine-readable error code
   */
  code: string | null;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * The parameter related to the error, if applicable
   */
  param?: string | null | undefined;
  /**
   * Unique request identifier for support
   */
  requestId: string;
};

/** @internal */
export const CustomerCreditsErrorDetailDtoType$inboundSchema: z.ZodNativeEnum<
  typeof CustomerCreditsErrorDetailDtoType
> = z.nativeEnum(CustomerCreditsErrorDetailDtoType);
/** @internal */
export const CustomerCreditsErrorDetailDtoType$outboundSchema: z.ZodNativeEnum<
  typeof CustomerCreditsErrorDetailDtoType
> = CustomerCreditsErrorDetailDtoType$inboundSchema;

/** @internal */
export const CustomerCreditsErrorDetailDto$inboundSchema: z.ZodType<
  CustomerCreditsErrorDetailDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CustomerCreditsErrorDetailDtoType$inboundSchema,
  code: z.nullable(z.string()),
  message: z.string(),
  param: z.nullable(z.string()).optional(),
  request_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});
/** @internal */
export type CustomerCreditsErrorDetailDto$Outbound = {
  type: string;
  code: string | null;
  message: string;
  param?: string | null | undefined;
  request_id: string;
};

/** @internal */
export const CustomerCreditsErrorDetailDto$outboundSchema: z.ZodType<
  CustomerCreditsErrorDetailDto$Outbound,
  z.ZodTypeDef,
  CustomerCreditsErrorDetailDto
> = z.object({
  type: CustomerCreditsErrorDetailDtoType$outboundSchema,
  code: z.nullable(z.string()),
  message: z.string(),
  param: z.nullable(z.string()).optional(),
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

export function customerCreditsErrorDetailDtoToJSON(
  customerCreditsErrorDetailDto: CustomerCreditsErrorDetailDto,
): string {
  return JSON.stringify(
    CustomerCreditsErrorDetailDto$outboundSchema.parse(
      customerCreditsErrorDetailDto,
    ),
  );
}
export function customerCreditsErrorDetailDtoFromJSON(
  jsonString: string,
): SafeParseResult<CustomerCreditsErrorDetailDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerCreditsErrorDetailDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerCreditsErrorDetailDto' from JSON`,
  );
}
