/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LicenseInstanceEntity,
  LicenseInstanceEntity$inboundSchema,
  LicenseInstanceEntity$Outbound,
  LicenseInstanceEntity$outboundSchema,
} from "./licenseinstanceentity.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";

export type LicenseInstanceListEntity = {
  /**
   * List of license instance items
   */
  items: Array<LicenseInstanceEntity>;
  /**
   * Pagination details for the list
   */
  pagination: PaginationEntity;
};

/** @internal */
export const LicenseInstanceListEntity$inboundSchema: z.ZodType<
  LicenseInstanceListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(LicenseInstanceEntity$inboundSchema),
  pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export type LicenseInstanceListEntity$Outbound = {
  items: Array<LicenseInstanceEntity$Outbound>;
  pagination: PaginationEntity$Outbound;
};

/** @internal */
export const LicenseInstanceListEntity$outboundSchema: z.ZodType<
  LicenseInstanceListEntity$Outbound,
  z.ZodTypeDef,
  LicenseInstanceListEntity
> = z.object({
  items: z.array(LicenseInstanceEntity$outboundSchema),
  pagination: PaginationEntity$outboundSchema,
});

export function licenseInstanceListEntityToJSON(
  licenseInstanceListEntity: LicenseInstanceListEntity,
): string {
  return JSON.stringify(
    LicenseInstanceListEntity$outboundSchema.parse(licenseInstanceListEntity),
  );
}
export function licenseInstanceListEntityFromJSON(
  jsonString: string,
): SafeParseResult<LicenseInstanceListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LicenseInstanceListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LicenseInstanceListEntity' from JSON`,
  );
}
