/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Lifecycle status of the product: `active` or `archived`.
 */
export const ProductStatus = {
  Active: "active",
  Archived: "archived",
} as const;
/**
 * Lifecycle status of the product: `active` or `archived`.
 */
export type ProductStatus = ClosedEnum<typeof ProductStatus>;

/** @internal */
export const ProductStatus$inboundSchema: z.ZodNativeEnum<
  typeof ProductStatus
> = z.nativeEnum(ProductStatus);
/** @internal */
export const ProductStatus$outboundSchema: z.ZodNativeEnum<
  typeof ProductStatus
> = ProductStatus$inboundSchema;
