/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of the feature: `custom` (private note), `file` (downloadable files), `licenseKey` (license key), or `customerCredits` (customer credit grant).
 */
export const ProductFeatureType = {
  Custom: "custom",
  File: "file",
  LicenseKey: "licenseKey",
  CustomerCredits: "customerCredits",
} as const;
/**
 * The type of the feature: `custom` (private note), `file` (downloadable files), `licenseKey` (license key), or `customerCredits` (customer credit grant).
 */
export type ProductFeatureType = ClosedEnum<typeof ProductFeatureType>;

/** @internal */
export const ProductFeatureType$inboundSchema: z.ZodNativeEnum<
  typeof ProductFeatureType
> = z.nativeEnum(ProductFeatureType);
/** @internal */
export const ProductFeatureType$outboundSchema: z.ZodNativeEnum<
  typeof ProductFeatureType
> = ProductFeatureType$inboundSchema;
