/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Billing method for the product: `recurring` subscription or `onetime` payment.
 */
export const ProductRequestBillingType = {
  Recurring: "recurring",
  Onetime: "onetime",
} as const;
/**
 * Billing method for the product: `recurring` subscription or `onetime` payment.
 */
export type ProductRequestBillingType = ClosedEnum<
  typeof ProductRequestBillingType
>;

/** @internal */
export const ProductRequestBillingType$inboundSchema: z.ZodNativeEnum<
  typeof ProductRequestBillingType
> = z.nativeEnum(ProductRequestBillingType);
/** @internal */
export const ProductRequestBillingType$outboundSchema: z.ZodNativeEnum<
  typeof ProductRequestBillingType
> = ProductRequestBillingType$inboundSchema;
