/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Status of the refund. `pending` and `requiresAction` represent non-terminal provider processing states.
 */
export const RefundStatus = {
  Pending: "pending",
  RequiresAction: "requiresAction",
  Succeeded: "succeeded",
  Failed: "failed",
  Canceled: "canceled",
} as const;
/**
 * Status of the refund. `pending` and `requiresAction` represent non-terminal provider processing states.
 */
export type RefundStatus = ClosedEnum<typeof RefundStatus>;

/** @internal */
export const RefundStatus$inboundSchema: z.ZodNativeEnum<typeof RefundStatus> =
  z.nativeEnum(RefundStatus);
/** @internal */
export const RefundStatus$outboundSchema: z.ZodNativeEnum<typeof RefundStatus> =
  RefundStatus$inboundSchema;
