/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RefundStatus,
  RefundStatus$inboundSchema,
  RefundStatus$outboundSchema,
} from "./refundstatus.js";

export type RefundResponseEntity = {
  /**
   * Status of the refund. `pending` and `requiresAction` represent non-terminal provider processing states.
   */
  status: RefundStatus;
};

/** @internal */
export const RefundResponseEntity$inboundSchema: z.ZodType<
  RefundResponseEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: RefundStatus$inboundSchema,
});
/** @internal */
export type RefundResponseEntity$Outbound = {
  status: string;
};

/** @internal */
export const RefundResponseEntity$outboundSchema: z.ZodType<
  RefundResponseEntity$Outbound,
  z.ZodTypeDef,
  RefundResponseEntity
> = z.object({
  status: RefundStatus$outboundSchema,
});

export function refundResponseEntityToJSON(
  refundResponseEntity: RefundResponseEntity,
): string {
  return JSON.stringify(
    RefundResponseEntity$outboundSchema.parse(refundResponseEntity),
  );
}
export function refundResponseEntityFromJSON(
  jsonString: string,
): SafeParseResult<RefundResponseEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefundResponseEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefundResponseEntity' from JSON`,
  );
}
