/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Additional metadata for the customer.
 */
export type UpdateCustomerRequestEntityMetadata = {};

export type UpdateCustomerRequestEntity = {
  /**
   * The ID of the customer to update.
   */
  customerId: string;
  /**
   * The full name of the customer.
   */
  name?: string | undefined;
  /**
   * Additional metadata for the customer.
   */
  metadata?: UpdateCustomerRequestEntityMetadata | undefined;
};

/** @internal */
export const UpdateCustomerRequestEntityMetadata$inboundSchema: z.ZodType<
  UpdateCustomerRequestEntityMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type UpdateCustomerRequestEntityMetadata$Outbound = {};

/** @internal */
export const UpdateCustomerRequestEntityMetadata$outboundSchema: z.ZodType<
  UpdateCustomerRequestEntityMetadata$Outbound,
  z.ZodTypeDef,
  UpdateCustomerRequestEntityMetadata
> = z.object({});

export function updateCustomerRequestEntityMetadataToJSON(
  updateCustomerRequestEntityMetadata: UpdateCustomerRequestEntityMetadata,
): string {
  return JSON.stringify(
    UpdateCustomerRequestEntityMetadata$outboundSchema.parse(
      updateCustomerRequestEntityMetadata,
    ),
  );
}
export function updateCustomerRequestEntityMetadataFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCustomerRequestEntityMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateCustomerRequestEntityMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCustomerRequestEntityMetadata' from JSON`,
  );
}

/** @internal */
export const UpdateCustomerRequestEntity$inboundSchema: z.ZodType<
  UpdateCustomerRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_id: z.string(),
  name: z.string().optional(),
  metadata: z.lazy(() => UpdateCustomerRequestEntityMetadata$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
  });
});
/** @internal */
export type UpdateCustomerRequestEntity$Outbound = {
  customer_id: string;
  name?: string | undefined;
  metadata?: UpdateCustomerRequestEntityMetadata$Outbound | undefined;
};

/** @internal */
export const UpdateCustomerRequestEntity$outboundSchema: z.ZodType<
  UpdateCustomerRequestEntity$Outbound,
  z.ZodTypeDef,
  UpdateCustomerRequestEntity
> = z.object({
  customerId: z.string(),
  name: z.string().optional(),
  metadata: z.lazy(() => UpdateCustomerRequestEntityMetadata$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
  });
});

export function updateCustomerRequestEntityToJSON(
  updateCustomerRequestEntity: UpdateCustomerRequestEntity,
): string {
  return JSON.stringify(
    UpdateCustomerRequestEntity$outboundSchema.parse(
      updateCustomerRequestEntity,
    ),
  );
}
export function updateCustomerRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCustomerRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCustomerRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCustomerRequestEntity' from JSON`,
  );
}
